sudo: required

services: 
  - docker

before_install:
  - docker build -t fluffy-react-test-container -f Dockerfile.test .

script:
  - docker run fluffy-react-test-container

before_deploy:
  - docker build -t fluffy-react-aws .

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/travis-deploy.sh
  on:
    branch: master

